# Generated by Django 3.0.5 on 2020-05-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200425_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.ProductModel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(blank=True, null=True, through='product.ProductStock', to='product.Event'),
        ),
    ]
